version: '2'
services:
 jenkins-master:
   container_name: jenkins-container
   build: ./dockers/jenkins
   ports:
     - 50000:50000
     - 8081:8080
   links:
     - dind:docker
   volumes:
     - ./dockers/jenkins/jenkins:/var/jenkins_home
   depends_on:
     - dind
     - mysql

 dind:
    container_name: dind
    image: docker:dind
    privileged: true
    expose:
      - 2375
    volumes:
      - ./dockers/jenkins/jenkins:/var/jenkins_home
 
 mysql:
    container_name: mysql-container
    image: mysql:5.5
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=""
